#!/bin/bash

# Gnome-Terminal is acting really strangely...  this is an effort to try to reduce and/or identify
# its strangeness.
#
# To break out of the loop, press ctrl-C



function ctrl_c() {
    stty icanon echo
    clear
    head -70 log
    exit;
}

trap ctrl_c INT

reset
./atypical_chars_search


#clear
#head -70 log
less log
